server:
  port: 8089
spring:
  cloud:
    gateway:
      # this is for the routes to be configured in the gateway
      routes:
        - id: parametre
          uri: lb://PARAMETRE
          predicates:
            - Path=/api/v1/parametre/**
        - id: media
          uri: lb://MEDIA
          predicates:
            - Path=/api/v1/media/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notification/**
        - id: demande
          uri: lb://DEMANDES
          predicates:
            - Path=/api/v1/demandes/**
  # this is for certificate validation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tawsal-express
          jwk-set-uri: http://localhost:8080/realms/tawsal-express/protocol/openid-connect/certs
# this is for the actuator endpoints to be exposed
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
# this is for service info to be shown in the eureka server
info:
  app:
    name: GatewayServer
    description: "This service is for the gateway server"
    version: 1.0.0
# this is for eureka client to register the service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true