server:
  port: 8088

# this is for the database connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5229/media-service
    username: media-service
    password: media-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    show-sql: true
  #this is for bus to notify the changes in the configurations to the services and refresh the configurations
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# this is for eureka client to register the service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# this is for file upload
file:
  storage:
    path: "/Users/ayoub/Desktop/File Data/"
    # path: "C:\\Users\\SetupGame\\Desktop\\File Data\\"
# this if for the actuator endpoints to be exposed
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
# this is for service info to be shown in the eureka server
info:
  app:
    name: media-service
    description: "This service is for the media management"
    version: 1.0.0
# this is for logging
logging:
  level:
    org:
      springframework:
        web: DEBUG

