server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5223/parametre-service
    username: parametre-service
    password: parametre-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"